[api_keys]

# Coinbase
coinbase_api_key = "organizations/2300e19b-1d24-40f0-b958-3df12e1308aa/apiKeys/ffdff2db-2b8c-41c3-84f8-82e4f0a123f4"

# CoinSpot
coinspot_api_key = "333e25604eb21e78b6d5942371b7ceb0"

# Crypto.com
crypto_api_key = "G2qNBm4uS1kijjddg8LDTy"

# Independent Reserve
independent_reserve_key = "baa135bf-0ecf-4d5c-9893-6434c3afc72c
"

# Kraken 
kraken_api_key = " laR7EcA3DPfhrN/j7RtMRRv3927UYzJgI1SjFJFdV0IteYwuQ4+xgtwL"
